# -*- coding: utf-8 -*-
#------------------------------------------------------------------------------#
# Copyright (C) [2026] Instituto Nacional de Estadística
#
# Este archivo forma parte del proyecto MLutils.
#
# Licenciado bajo la Licencia Pública de la Unión Europea (EUPL) v.1.2.
# Puede obtener una copia de la licencia en la raiz de este proyecto o en:
# https://eupl.eu/1.2/es/
#
# A menos que se indique lo contrario, este software se distribuye
# "TAL CUAL", SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO.
# Consulte la licencia para conocer los términos específicos.
#------------------------------------------------------------------------------#
# Copyright (C) [2026] National Institute of Statistics
#
# This file is part of the MLutils project.
#
# Licensed under the European Union Public License (EUPL) v.1.2.
# You can obtain a copy of the license at the root of this project or at:
# https://eupl.eu/1.2/es/
#
# Unless otherwise indicated, this software is distributed
# "AS IS", WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND.
# See the license for specific terms.
#------------------------------------------------------------------------------#

#' @title Trains a modeler object.
#'
#' @description Fits the model in the modeler generated by \code{\link{modeler}} container to the given data.
#'
#' @param object \code{\link{modeler}} object to fit to the data.
#' @param data Dataframe containing the data to use for the training
#' @param subSet Optional value, select a subSet of the data for the training.
#' @param val_data Optional value for catbostModeler objects. Used as validation set during training.
#'
#'
#' @return A trained modeler object, which contains some of the details and metrics
#' after training.
#'
#' @import data.table
#'
#' @examples
#' #Generate data
#' data.dt <- generateRegressionData(n_samples = 1000, generate_random_weights = FALSE)
#'
#' #Define train/test partitions
#' set.seed(273)
#' data.keys <- 1:nrow(data.dt)
#' train_size = round(0.8 * nrow(data.dt))
#' smplr <- srsSampler(key = data.keys, ssize = train_size)
#' train.keys <- getSample(smplr)
#' test.keys <- setdiff(data.keys, train.keys)
#'
#' #Define modeler
#' params <- list(
#'   "num.trees" = 50,
#'   "max.depth" = 20
#' )
#' target <- "regression_target"
#' regressors <- setdiff(colnames(data.dt), target)
#'
#' modeler <- rangerRegressorModeler(params = params, target = target, regressors = regressors)
#'
#' #Train modeler
#' modeler <- train(object = modeler, data = data.dt, subSet = train.keys)
#' @export
train <- function(object, data, subSet = NULL) {
  UseMethod("train")
}
#' @rdname train
#' @export
train.directModeler <- function(object, data, subSet = NULL) {
  return(object)
}
#' @rdname train
#' @import data.table
#' @export
train.HTModeler <- function(object, data, subSet = NULL) {
  target <- getTarget(object)
  weightsColumn <- object$weightsColumn

  #Validate target, subSet and filter data
  RMLutils:::.validate_target(object = object, data = data)
  data <- RMLutils:::.validate_generic_data_subset(data = data,
                                        subSet = subSet,
                                        target = target)

  if (!(weightsColumn %in% colnames(data))) {
    stop("Weights column is missing from data set.")
  }

  weights <- as.matrix(data[, get(weightsColumn)])[,1]
  vars <- as.matrix(data[, get(target)])[,1]

  #Re-escale weights
  weights <- (weights - 1) / (length(weights) - sum(1 / weights))
  #Calculate weighted average factor
  object$trainedModel <- list(factorMean = sum(weights * vars))
  #Set boolean trained flag
  object$isTrained <- TRUE
  return(object)
}

#' @rdname train
#' @export
train.strataHTModeler <- function(object, data, subSet = NULL) {
  target <- getTarget(object)
  weightsColumn <- object$weightsColumn

  #Validate target, subSet and filter data
  RMLutils:::.validate_target(object = object, data = data)
  data <- RMLutils:::.validate_generic_data_subset(data = data,
                                        subSet = subSet,
                                        target = target)
  if (!(weightsColumn %in% colnames(data))) {
    stop("Weights column is missing from data set.")
    }

  object$trainedModel$factorMeanStrata <- data[,
    sum(((get(weightsColumn) - 1) / (length(get(weightsColumn))
                                            - sum(1 / get(weightsColumn)))) * get(target)),
    by = eval(object$strata)]
  setnames(object$trainedModel$factorMeanStrata, "V1", target)

  object$trainedModel$factorMeanGeneral <- data[,
    sum(((get(weightsColumn) - 1) / (length(get(weightsColumn))
                                            - sum(1 / get(weightsColumn)))) * get(target))]
  #Set boolean trained flag
  object$isTrained <- TRUE
  return(object)
}

#' @rdname train
#' @importFrom stats weighted.mean
#' @export
train.strataMeanModeler <- function(object, data, subSet = NULL) {
  RMLutils:::.validate_target(object = object, data = data)
  data <- RMLutils:::.validate_generic_data_subset(data = data,
                                        subSet = subSet,
                                        target = object$target)
  #Check that regressors are categorical
  if(!all(sapply(data[, .SD, .SDcols = object$regressors],class) %in% c("character", "factor"))){
    stop("Some of the regressor variables are not categorical or characters.")
  }
  if (object$weightsColumn == "") {
    object$trainedModel$strata <- data[,
                              mean(get(object$target)),
                              by = eval(object$regressors)]
    setnames(object$trainedModel$strata, "V1", object$target)
    object$trainedModel$general <- data[,
                                        mean(get(object$target))]

  } else {
    object$trainedModel$strata <- data[,
                  weighted.mean(get(object$target), get(object$weightsColumn)),
                  by = eval(object$regressors)]
    setnames(object$trainedModel$strata, "V1", object$target)
    object$trainedModel$general <- data[,
                weighted.mean(get(object$target), get(object$weightsColumn))]
  }
  #Set boolean trained flag
  object$isTrained <- TRUE
  return(object)
}

#' @rdname train
#' @export
train.H2OModeler <- function(object, data, subSet = NULL) {
  movedData <- FALSE

  #TODO: Check that it works with H2OFrames (do the same with getPredictions)
  data <- RMLutils:::.validate_H2O_data_subset(data = data,
                                               subSet = subSet,
                                               target = object$target)
  RMLutils:::.validate_target_H2OModeler(object = object, data = data)

  if (!inherits(data, "H2OFrame")) {

    is.fact <- sapply(data, is.factor)
    for(nm in names(is.fact)){
      if(is.fact[nm]){
        data[, (nm) := factor(get(nm), ordered = FALSE)]
      }
    }
    #Check whether the target variable is categorical type and automatically set the class_names
    if(is.factor(data[[getTarget(object)]])){
      object$class_names <- levels(data[[getTarget(object)]])
    }

    data <- h2o::as.h2o(data)
    movedData <- TRUE
  }else{
    #Check whether the target variable is categorical type (enum) and automatically set the class_names
    if(h2o.getTypes(data[getTarget(object)])[[1]] == "enum"){
      object$class_names <- h2o::h2o.levels(data[[getTarget(object)]])
    }
  }

  arguments <- c(list(x = getRegressors(object), y = getTarget(object),
                        training_frame = data), object$params)
  object <- modelClean(object)
  object$trainedModel <- do.call(getFromNamespace(paste0("h2o.", object$model), "h2o"), arguments)
  if (movedData) h2o::h2o.rm(list(data))
  #Delete garbage from cloud
  current_cloud_elements <- as.character(h2o::h2o.ls()$key)
  h2o::h2o.rm(grep(pattern = "metrics", x = current_cloud_elements, value = TRUE))
  #Set boolean trained flag
  object$isTrained <- TRUE
  return(object)
}

#' @rdname train
#' @export
train.benchModeler <- function(object, data, subSet = NULL) {
  # Train submodels
  object$submodels <- lapply(
    object$submodels,
    train,
    data,
    subSet
  )

  # Optimization weights
  if (object$optWeights == "uniform") {
    w <- rep(1, length(object$target))

  } else if (object$optWeights == "MSE") {
    mse <- unlist(sapply(
      object$submodels,
      function(x) evaluate(x, data, MSECostFunction())
    ))
    w <- 1 / mse
  }

  # P matrix
  object$P <- Matrix::Diagonal(
    n = length(object$target),
    x = w
  )
  #Set boolean trained flag
  object$isTrained <- TRUE
  return(object)
}

#' @rdname train
#' @export
train.preproModeler <- function(object, data, subSet = NULL) {
  #Validate target, subSet and filter data
  RMLutils:::.validate_target(object = object, data = data)
  data <- RMLutils:::.validate_generic_data_subset(data = data,
                                        subSet = subSet,
                                        target = getTarget(object))

  #TODO: This could be done externally instead of here
  #if(object$modeler$model == "mice"){
  #  object$preproObject$params$mode <- "train"
  #}

  #Make getPreproData do all the work preprocessing
  #preproObject$data is now the preprocessed data
  object$preproObject <- getPreproData(object = object$preproObject, data = data)
  trainDF <- object$preproObject$data#Extract preprocessed data

  #Assign new regressors to object and internal modeler
  object <- setRegressors(object = object, newRegressors = object$preproObject$new_regressors)
  #object$modeler$regressors <- object$preproObject$new_regressors

  #Overwrite object$modeler with the trained modeler
  object$modeler <- train(object = object$modeler, data = trainDF, subSet = NULL)

  #Set boolean trained flag
  object$isTrained <- TRUE
  return(object)
}

#' @rdname train
#' @export
train.LGBModeler <- function(object, data, subSet = NULL) {

  #Validate target, subSet and filter data
  RMLutils:::.validate_target(object = object, data = data)
  data <- RMLutils:::.validate_generic_data_subset(data = data,
                                        subSet = subSet,
                                        target = getTarget(object))

  if(!is.null(object$params$weight_column)){
    weights_values <- data[subSet, get(object$params$weight_column)]
  }else{
    weights_values <- rep(1, nrow(data[subSet]))
  }
  #Filter regressors before finding categorical variables
  if(class(object)[3] == "classifierModeler"){
    #Get levels of target variable
    t.levels <- levels(data[[object$target]])
    #Assign direct levels to class_names
    object$class_names <- t.levels
    if(object$params$objective == "binary"){
      if(length(t.levels)!=2){
        stop("Target variable is not binary. Please review your data.")
      }
      #Check if positive_class was provided
      if(!is.null(object$positive_class)){
        if((!object$positive_class %in% t.levels)){
          stop("The provided positive_class was not found in the data, please review your inputs.")
        }
        #Map negative and positive class to their actual indexing in LightGBM
        #0 is negative and 1 is positive
        negative_class <- t.levels[t.levels != object$positive_class]
        t.levels_mapping <- 0:1
        names(t.levels_mapping) <- c(negative_class, object$positive_class)
        data[,(object$target) := t.levels_mapping[as.character(get(object$target))]]
        #data2 <- copy(data)
        #data2[,new_target := t.levels_mapping[as.character(get(object$target))]]
      }else{#If it was not provided, throw warning
        warning("positive_class was not set when defining the modeler. Assuming first category to be the negative one and last category to be the positive one.")
        #Proceed with ordinal encoding (and substracting 1 to make it work with LightGBM)
        data[,(object$target) := as.numeric(get(object$target)) - 1]
      }
    }else{#If objective is multiclass:
      #If objective is not binary and positive_class was provided, throw warning
      if(!is.null(object$positive_class)){
        warning("A positive_class was provided, but objective is different from binary. This parameter will be unused.")
      }

      #Proceed with ordinal encoding (and substracting 1 to make it work with LightGBM)
      data[,(object$target) := as.numeric(get(object$target)) - 1]
    }


    targ <- data.matrix(data[, object$target, with= FALSE])
  }else{
    targ <- data.matrix(data[, object$target, with= FALSE])
  }

  data <- data[, object$regressors, with=FALSE]

  #Automatically find categorical variables
  is.fact <- sapply(data, is.factor)
  if(sum(is.fact) > 0){
    ifCategVars <- TRUE
    categVars <- names(is.fact)[is.fact]
    #If the target variable is categorical, save its levels in the modeler object
    #if(object$target %in% names(is.fact)){
    #  object$class_names <- levels(data[[object$target]])
    #  data[, object$target := as.integer(get(object$target)) - 1]
    #  categVars <- categVars[!categVars %in% c(object$target)]
    #}
    #Then, convert categorical columns into integer, starting from 0 (necessary for lightgbm)
    data[, (categVars) := lapply(.SD, function(x) as.integer(x) - 1), .SDcols = categVars]
  }else{
    ifCategVars <- FALSE
  }

  data.mat <- data.matrix(data)

  if(ifCategVars){
    lgb.dy1 <- lightgbm::lgb.Dataset(data = data.mat,#[, colnames(data.mat) != object$target, drop = F],
                                     label = targ,
                                     weight = weights_values,
                                     categorical_feature = categVars)
  }else{
    lgb.dy1 <- lightgbm::lgb.Dataset(data = data.mat,#[, colnames(data.mat) != object$target, drop = F],
                                     label = targ,
                                     weight = weights_values)
  }
  #Clean model in case there was a trained model previously
  object <- modelClean(object)

  object$trainedModel <- lightgbm::lgb.train(data = lgb.dy1,
                                              nrounds = object$params$nrounds,
                                              params = object$params)
  #Set boolean trained flag
  object$isTrained <- TRUE
  return(object)
}

#' @rdname train
#' @export
train.rangerModeler <- function(object, data, subSet = NULL) {

  #Validate target, subSet and filter data
  RMLutils:::.validate_target(object = object, data = data)
  data <- RMLutils:::.validate_generic_data_subset(data = data,
                                        subSet = subSet,
                                        target = getTarget(object))

  #Check whether the target variable is categorical type and automatically set the classification parameter
  if(is.factor(data[[object$target]])){
    object$params$classification <- TRUE
    object$params$probability <- TRUE#This forces the model to return probabilities when using predict()
    object$class_names <- levels(data[[object$target]])
  }else{
    object$params$classification <- FALSE
  }


  #if(!is.null(object$params$weight_column)){
  if(!is.null(object$params$case.weights)){
    weights_values <- data[, get(object$params$case.weights)]
  }else{
    weights_values <- rep(1, nrow(data))
  }

  # Se limpia modelo entrenado en caso de que haya
  object <- modelClean(object)

  parametros <- object$params
  parametros$case.weights <- weights_values
  parametros$model_name <- NULL
  parametros$target <- NULL
  parametros$data <- data
  parametros$formula <- formula(eval(parse(text=paste0(paste0(object$target, "~"),paste0(object$regressors, collapse = "+")))))
  object$trainedModel <- do.call(ranger::ranger, args = parametros )

  #Set boolean trained flag
  object$isTrained <- TRUE
  return(object)
}

#' @rdname train
#' @export
train.catboostModeler <- function(object, data, subSet = NULL) {

  #Assign validation data (if it exists)
  val_data <- object$val_data

  #Validate target, subSet and filter data
  RMLutils:::.validate_target(object = object, data = data)
  data <- RMLutils:::.validate_generic_data_subset(data = data,
                                        subSet = subSet,
                                        target = getTarget(object))

  regressors.dt <- data[, object$regressors, with=FALSE]
  #TODO: Re-level target to make sure negative and positive classes are
  #properly assigned.

  if(class(object)[3] == "classifierModeler"){#Classification
    #Get levels of target variable
    t.levels <- levels(data[[object$target]])
    #Assign direct levels to class_names
    object$class_names <- t.levels
    if(object$params$loss_function %in% c("Logloss","CrossEntropy")){#Binary
      if(length(t.levels)!=2){
        stop("Target variable is not binary. Please review your data.")
      }
      #Check if positive_class was provided
      if(!is.null(object$positive_class)){
        if((!object$positive_class %in% t.levels)){
          stop("The provided positive_class was not found in the data, please review your inputs.")
        }
        #Find negative class
        negative_class <- t.levels[t.levels != object$positive_class]

        #Re-level target variable factor levels so that the first one is the
        #negative class and the last one, the positive one
        #The same will be done for the validation set
        target <- data[, get(object$target)]
        target <- factor(target, levels = c(negative_class, object$positive_class))

      }else{#If it was not provided, throw warning
        warning("positive_class was not set when defining the modeler. Assuming first category to be the negative one and last category to be the positive one.")
        target <- data[, get(object$target)]
      }
    }else{#Multiclass
      target <- data[, get(object$target)]
    }
  }else{#Regression
    target <- data[, get(object$target)]
  }

  if(!is.null(object$params$weight_column)){
    weights_values <- data[, get(object$params$weight_column)]
  }else{
    weights_values <- rep(1, nrow(data))
  }

  pool_train <- catboost::catboost.load_pool(regressors.dt,
                                  label = target,
                                  weight = weights_values)
  if(!is.null(val_data)){
    val_data <- as.data.table(val_data)#Force conversion just in case
    if(!is.null(object$params$weight_column)){
      val_weights_values <- val_data[, get(object$params$weight_column)]
    }else{
      val_weights_values <- rep(1, nrow(val_data))
    }
    val_regressors.dt <- val_data[subSet, object$regressors, with=FALSE]
    #If it's a binary classification target and object$positive_class is not null
    if(object$params$loss_function %in% c("Logloss","CrossEntropy") & !is.null(object$positive_class)){
      val_target <- val_data[, get(object$target)]
      val_target <- factor(val_target, levels = c(negative_class, object$positive_class))
    }else{
      val_target <- val_data[, get(object$target)]
    }

    pool_val <-  catboost::catboost.load_pool(val_regressors.dt,
                                    label = val_target,
                                    weight = val_weights_values)
  }else{
    pool_val <- NULL
  }

  # Se limpia modelo entrenado en caso de que haya
  object <- modelClean(object)

  #Considerar si añadir validación al entrenamiento (el modelo lo permite)
  object$trainedModel <- catboost::catboost.train(learn_pool = pool_train,
                                                  test_pool = pool_val,
                                                  params = object$params)
  #Set boolean trained flag
  object$isTrained <- TRUE
  return(object)
}


#' @rdname train
#' @export
train.miceModeler <- function(object, data, subSet = NULL) {

  #Validate target, subSet and filter data
  RMLutils:::.validate_target(object = object, data = data)
  data <- RMLutils:::.validate_generic_data_subset(data = data,
                                        subSet = subSet,
                                        target = getTarget(object))

  #Check whether the target variable is categorical type and assign class_names if so
  if(is.factor(data[[object$target]])){
    object$class_names <- levels(data[[object$target]])
  }

  # Clean trainedModel if it exists and assign new data as trained model
  object <- modelClean(object)
  object$trainedModel <- copy(data)

  #This assumes that there are no more columns besides target and regressors
  #Note that if there is a weightsColumn this may cause issues
  if(is.null(object$regressors)){
    warning("No regressors were defined, assuming all variables besides target are regressors.")
    object$regressors <- setdiff(colnames(object$trainedModel), object$target)
  }

  object$tipo_target <- class(object$trainedModel[, get(object$target)])

  #Set boolean trained flag
  object$isTrained <- TRUE
  return(object)
}

#' @rdname train
#' @export
train.prePredModeler <- function(object, data, subSet = NULL) {

  data <- RMLutils:::.validate_generic_data_subset(data = data,
                                        subSet = subSet)

  # Get initial models predictions
  object$predModeler <- RMLutils::train(object = object$predModeler, data = data)
  preds <- RMLutils::getPredictions(object$predModeler, data)
  # Add predictions to data copy
  dataCopy <- as.data.table(data)
  dataCopy[, colnames(preds) := as.data.table(preds)]
  # Train main model
  object$mainModeler <- RMLutils::train(object$mainModeler, dataCopy)
  # Remove data copy
  rm(dataCopy)
  #Set boolean trained flag
  object$isTrained <- TRUE
  return(object)
}

#' @rdname train
#' @export
train.classifRegModeler <- function(object, data, subSet = NULL) {

  RMLutils:::.validate_target(object = object, data = data)
  data <- RMLutils:::.validate_generic_data_subset(data = data,
                                        subSet = subSet,
                                        target = getTarget(object))
  # train the classification model
  #Data is already filtered here
  classifSubset <- 1:nrow(data)

  object <- modelClean(object)
  target <- as.matrix(data[[object$target]])[,1]

  if (object$epsilon == 0) {
    data[[paste0(object$target,"CAT")]] <- factor(
      ifelse(target %in% object$specialCats,
             target,
             "NOSP"),
      levels = c(object$specialCats, "NOSP")
    )
  } else {
    data[[paste0(object$target,"CAT")]] <- factor(
      sapply(lapply(target, function(y) abs(y - object$specialCats)), function(dif){
        ifelse(any(dif < object$epsilon),
               object$specialCats[which(dif < object$epsilon)],
               "NOSP")}),
      levels = c(object$specialCats, "NOSP")
    )
  }

  object$classifModeler <- setTarget(object$classifModeler, paste0(object$target,"CAT"))
  object$classifModeler <- RMLutils::train(object$classifModeler, data, classifSubset)

  # select the non special elements of the training data
  regSubset <- classifSubset[which(
    as.matrix(data[[paste0(object$target,"CAT")]])[classifSubset, 1] == "NOSP")]
  object$trainedModel <- list()

  data[, paste0(object$target,"CAT") := NULL]

  # train the regression model
  if (length(regSubset) > object$minRows) {
    object$regModeler <- RMLutils::train(object$regModeler, data, regSubset)
  } else {
    if (inherits(data,"H2OFrame")) {
      object$trainedModel$nonCatsMean <- h2o.mean(data[regSubset, object$target])
    } else {
      object$trainedModel$nonCatsMean <- mean(data[[object$target]][regSubset])
    }
  }
  #Set boolean trained flag
  object$isTrained <- TRUE
  return(object)
}


#' @rdname train
#' @export
train.memoryModeler <- function(object, data, subSet = NULL) {
  #Check if current data and previous data have the same columns
  if(!all(colnames(data) %in% colnames(data.table::rbindlist(object$data, fill = TRUE)))){
    stop(paste0("Current training data structure does not match the memoryModeler internal data structure.\n ",
                "Current training data columns: ", paste0(colnames(data), collapse = ", "),
                "\n ",
                "MemoryModeler data columns: ", paste0(colnames(data.table::rbindlist(object$data, fill = TRUE)))))
  }
  object$modeler <- train(object$modeler,
                          data.table::rbindlist(append(list(data), object$data), fill = FALSE),
                          subSet)
  #Set boolean trained flag
  object$isTrained <- TRUE
  return(object)
}
